language: python
python:
  - "3.5"
  - "3.5-dev" 
  - "nightly" 
# command to install dependencies
install: 
  - "pip install -r requirements.txt"
  - pip install coverage
  - pip install coveralls
# command to run tests
#script: coverage run --source=backend -m unittest discover
after_success:
  coveralls
