language: python
python:
  - "3.5"
  - "3.5-dev" 
  - "nightly" 
# command to install dependencies
install: 
  - "pip install -r requirements.txt"
  - pip install nose
  - pip install coveralls
# command to run tests
script: nosetests --with-coverage
after_success:
  coveralls
