language: python
python:
  - "3.5"
  - "3.5-dev" 
  - "nightly" 
# command to install dependencies
install: 
  - "pip install -r requirements.txt"
  - pip install coverage
  - pip install coveralls
# command to run tests
script: python3.5 -m unittest discover
#script: coverage run tests.py
after_success:
  coveralls
