language: python
python:
  - "3.5"
  - "3.5-dev" 
  - "nightly" 
# command to install dependencies
install: 
  - "pip install -r requirements.txt"
  - pip install coveralls
# command to run tests
script: python tests.py --pep8 coveralls -v --cov coveralls --cov-report term-missing
after_success:
  coveralls
